# Generated by Django 5.1.1 on 2024-10-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='ReservationDay',
        ),
        migrations.DeleteModel(
            name='SimpleReservation',
        ),
    ]
