# Generated by Django 5.1.1 on 2024-10-06 20:23

import django.core.files.storage
import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of Tour', max_length=250, null=True)),
                ('name_search', models.CharField(help_text='Tour Name Search', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Tour Description', null=True)),
                ('price', models.CharField(default='', max_length=250, null=True)),
                ('spot', models.IntegerField(blank=True, default=50, help_text='Cupos del Tour', null=True)),
                ('photo', models.FileField(blank=True, default='default/tour.jpeg', help_text='Photo of Tour', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/moisesbarrera/Documents/FundacionSewell/reservastours/public'), upload_to=reservas.models.tours_images_tours_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update Date', null=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tour',
            },
        ),
    ]
