# Generated by Django 5.1.1 on 2024-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='expiration',
            field=models.DateTimeField(auto_now=True, help_text='Expiration Date', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_expirated',
            field=models.BooleanField(blank=True, default=False, help_text='True if tour is expirated or cancelled'),
        ),
    ]
