# Generated by Django 5.1.1 on 2024-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_tour_expiration_tour_is_expirated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='expiration',
            field=models.DateTimeField(help_text='Expiration Date'),
        ),
    ]
