# Generated by Django 5.1.1 on 2024-10-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_tour_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='spot',
        ),
        migrations.CreateModel(
            name='DailyTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('spot', models.IntegerField(blank=True, default=10, help_text='Cupos de la reserva diaria', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('tour', models.ForeignKey(blank=True, help_text='Tour', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.tour')),
            ],
            options={
                'verbose_name': 'DailyTour',
                'verbose_name_plural': 'DailyTour',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='tour_day',
            field=models.ForeignKey(blank=True, help_text='Tour', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.dailytour'),
        ),
    ]
