# Generated by Django 5.1.1 on 2024-10-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_reservation_tour_remove_tour_spot_dailytour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='expiration',
            new_name='expiration_date',
        ),
        migrations.AddField(
            model_name='tour',
            name='activation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Activation Date', null=True),
        ),
    ]
