# Generated by Django 5.1.1 on 2024-10-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_holiday_rename_expiration_tour_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='activation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Activation Date'),
        ),
    ]
