# Generated by Django 5.1.1 on 2024-10-10 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_tour_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='activation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Activation Date'),
        ),
    ]
