# Generated by Django 5.1.1 on 2024-10-10 01:22

import django.core.files.storage
import django.db.models.deletion
import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_dailytour_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Additional photo of the tour', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/moisesbarrera/Documents/FundacionSewell/reservastours/public'), upload_to=reservas.models.tours_images_tours_directory_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservas.tour')),
            ],
        ),
    ]
